//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visibility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visibility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PluginCommandHelpMessage&quot;: &quot;Shows the config for the visibility plugin.\\nAdditional help available via &apos;/pvis help&apos;&quot;,
        ///  &quot;VoidPlayerHelpMessage&quot;: &quot;Adds player to void list.\\nUsage: /void &lt;firstname&gt; &lt;lastname&gt; &lt;worldname&gt; &lt;reason&gt;&quot;,
        ///  &quot;VoidTargetPlayerHelpMessage&quot;: &quot;Adds targeted player to void list.\\nUsage: /voidtarget &lt;reason&gt;&quot;,
        ///  &quot;WhitelistPlayerHelpMessage&quot;: &quot;Adds player to whitelist.\\nUsage: /whitelist &lt;firstname&gt; &lt;lastname&gt; &lt;worldname&gt;&quot;,
        ///  &quot;WhitelistTargetPlayerHelpMessage&quot;: &quot;Adds targeted pla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_strings {
            get {
                return ResourceManager.GetString("en.strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PluginCommandHelpMessage&quot;: &quot;Muestra la configuración del plugin de visibilidad.\\nUsa el comando &apos;/pvis help&apos; para recibir ayuda adicional&quot;,
        ///  &quot;VoidPlayerHelpMessage&quot;: &quot;Añade un jugador a la lista de vacío.\\nUso: /void &lt;nombre&gt; &lt;apellido&gt; &lt;mundo&gt; &lt;razón&gt;&quot;,
        ///  &quot;VoidTargetPlayerHelpMessage&quot;: &quot;Añade el jugador seleccionado a la lista de vacío.\\nUso: /voidtarget &lt;razón&gt;&quot;,
        ///  &quot;WhitelistPlayerHelpMessage&quot;: &quot;Añade un jugador a la lista de excepciones.\\nUso: /whitelist &lt;nombre&gt; &lt;apellido&gt; &lt;mundo&gt;&quot;,
        ///  &quot;Whiteli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string es_ES_strings {
            get {
                return ResourceManager.GetString("es-ES.strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PluginCommandHelpMessage&quot;: &quot;Montre la configuration pour le plugin Visibility.\\nDe l&apos;aide additionnelle est disponible via \&quot;/pvis help\&quot;&quot;,
        ///  &quot;VoidPlayerHelpMessage&quot;: &quot;Ajoute un joueur à la Voidlist.\\nUtilisation : /void &lt;prénom&gt; &lt;nom&gt; &lt;monde&gt; &lt;motif&gt;&quot;,
        ///  &quot;VoidTargetPlayerHelpMessage&quot;: &quot;Ajoute le joueur ciblé à la Voidlist.\\nUtilisation : /voidtarget &lt;motif&gt;&quot;,
        ///  &quot;WhitelistPlayerHelpMessage&quot;: &quot;Ajoute un joueur à la Whitelist.\\nUtilisation : /void &lt;prénom&gt; &lt;nom&gt; &lt;monde&gt;&quot;,
        ///  &quot;WhitelistTargetPlayerHelp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr_strings {
            get {
                return ResourceManager.GetString("fr.strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PluginCommandHelpMessage&quot;: &quot;Mostra la configurazione per il plugin di visibilità.\\nAiuto aggiuntivo disponibile tramite &apos;/pvis help&apos;&quot;,
        ///  &quot;VoidPlayerHelpMessage&quot;: &quot;Aggiunge il giocatore alla lista del vuoto.\\nUso: /void &lt;firstname&gt; &lt;lastname&gt; &lt;worldname&gt; &lt;reason&gt;&quot;,
        ///  &quot;VoidTargetPlayerHelpMessage&quot;: &quot;Aggiunge il giocatore alla lista del vuoto.\\nUso: /void &lt;reason&gt;&quot;,
        ///  &quot;WhitelistPlayerHelpMessage&quot;: &quot;Aggiunge il giocatore alla lista bianca.\\nUso: /whitelist &lt;firstname&gt; &lt;lastname&gt; &lt;worldname&gt;&quot;,
        ///  &quot;Whitel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string it_strings {
            get {
                return ResourceManager.GetString("it.strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PluginCommandHelpMessage&quot;: &quot;Mostra a configuração para o plugin visibility.\\nAjuda adicional disponível através do comando &apos;/pvis help&apos;&quot;,
        ///  &quot;VoidPlayerHelpMessage&quot;: &quot;Adiciona o jogador à lista nula. \\nUso: /void &lt;nome&gt; &lt;sobrenome&gt; &lt;mundo&gt; &lt;motivo&gt;&quot;,
        ///  &quot;VoidTargetPlayerHelpMessage&quot;: &quot;Adiciona o jogador alvo à lista nula. \\nUso: /voidtarget &lt;motivo&gt;&quot;,
        ///  &quot;WhitelistPlayerHelpMessage&quot;: &quot;Adiciona o jogador à lista branca.\\nUso: /whitelist &lt;nome&gt; &lt;sobrenome&gt; &lt;mundo&gt;&quot;,
        ///  &quot;WhitelistTargetPlayerHelpMessage&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pt_BR_strings {
            get {
                return ResourceManager.GetString("pt-BR.strings", resourceCulture);
            }
        }
    }
}
